modLoader = "javafml"
loaderVersion = "[40,)"
license = "All Rights Reserved"
[[mods]]
modId = "fancychunks"
version = "${file.jarVersion}"
displayName = "Fancy Chunks"
authors = "HollowHorizon, AlgorithmLX"
description = '''
smooth chunk loading
'''
[[dependencies.fancychunks]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fancychunks]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fancychunks]]
modId = "rubidium"
mandatory = true
versionRange = "[0.5.6,)"
ordering = "NONE"
side = "BOTH"

#Oculus optional dependency
[[dependencies.fancychunks]]
modId = "oculus"
mandatory = false
versionRange = "[1.6.4,)"
ordering = "NONE"
side = "BOTH"
